#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
README_FILE="$ROOT_DIR/README.md"
PROGRESS_FILE="$ROOT_DIR/EXACT_SIM_PROGRESS.md"

grep -q 'LONGTARGET_ENABLE_SIM_CUDA_REGION_REDUCE=1' "$README_FILE"
grep -q 'experimental' "$README_FILE"
grep -q 'benchmark.sim_region_events_total' "$README_FILE"
grep -q 'benchmark.sim_region_candidate_summaries_total' "$README_FILE"
grep -q 'benchmark.sim_region_event_bytes_d2h' "$README_FILE"
grep -q 'benchmark.sim_region_summary_bytes_d2h' "$README_FILE"
grep -q 'benchmark.sim_region_cpu_merge_seconds' "$README_FILE"
grep -q 'benchmark.sim_locate_total_cells' "$README_FILE"
grep -q 'LONGTARGET_ENABLE_SIM_CUDA_LOCATE=1' "$README_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_MODE=safe_workset' "$README_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_MODE=fast' "$README_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_FAST_SHADOW=1' "$README_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_FAST_PAD' "$README_FILE"
grep -q 'benchmark.sim_locate_backend' "$README_FILE"
grep -q 'benchmark.sim_locate_mode' "$README_FILE"
grep -q 'benchmark.sim_locate_fast_passes' "$README_FILE"
grep -q 'benchmark.sim_locate_fast_fallbacks' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_passes' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_affected_starts' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_unique_affected_starts' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_exec_bands' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_cuda_launches' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_returned_states' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_build_seconds' "$README_FILE"
grep -q 'benchmark.sim_safe_workset_merge_seconds' "$README_FILE"
grep -q 'benchmark.sim_locate_gpu_seconds' "$README_FILE"
grep -q 'benchmark.sim_fast_workset_bands' "$README_FILE"
grep -q 'benchmark.sim_fast_segments' "$README_FILE"
grep -q 'benchmark.sim_fast_fallback_shadow_candidate_value' "$README_FILE"

grep -q 'runningMin' "$PROGRESS_FILE"
grep -q 'LONGTARGET_ENABLE_SIM_CUDA_REGION_REDUCE=1' "$PROGRESS_FILE"
grep -q 'benchmark.sim_region_events_total' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_total_cells' "$PROGRESS_FILE"
grep -q 'LONGTARGET_ENABLE_SIM_CUDA_LOCATE=1' "$PROGRESS_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_MODE=safe_workset' "$PROGRESS_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_MODE=fast' "$PROGRESS_FILE"
grep -q 'LONGTARGET_SIM_CUDA_LOCATE_FAST_SHADOW=1' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_backend' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_mode' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_fast_passes' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_fast_fallbacks' "$PROGRESS_FILE"
grep -q 'benchmark.sim_locate_gpu_seconds' "$PROGRESS_FILE"
grep -q 'benchmark.sim_fast_workset_bands' "$PROGRESS_FILE"
grep -q 'benchmark.sim_fast_segments' "$PROGRESS_FILE"
grep -q 'benchmark.sim_fast_fallback_shadow_candidate_value' "$PROGRESS_FILE"
grep -q '单个 start key 只回传一个 summary' "$PROGRESS_FILE"
